version: '3'
services:
  php:
    container_name: webserver
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dev:/var/www/html
      - ./php-conf:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    ports:
      - ${IP}:${PORT}:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - ${IP}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./db-data:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 50M
    depends_on:
      - db
    ports:
      - ${IP}:${PHPMYADMIN_PORT}:80
    links:
      - db:db
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - ${IP}:${ADMINER_PORT}:8080